// v32 Study-guide-aligned questions patch
// Injects additional questions into CSE_DATA.questions after data.js loads
(function() {
  if (!window.CSE_DATA || !window.CSE_DATA.questions) return;

  const Q = window.CSE_DATA.questions;

  const newQ = [
    // WEEK 1: Number Properties
    { id:"v32q0001", kind:"scored", topic:"numerical", subtopic:"Number Properties", difficulty:"easy",
      q:"Which of the following is a prime number?",
      choices:["9","15","17","21"], answer:2,
      shortcut:"A prime has exactly 2 factors: 1 and itself.",
      explanation:"17 is only divisible by 1 and 17. 9=3×3, 15=3×5, 21=3×7." },
    { id:"v32q0002", kind:"scored", topic:"numerical", subtopic:"Integers", difficulty:"easy",
      q:"What is the absolute value of -38?",
      choices:["−38","38","0","−1"], answer:1,
      shortcut:"|n| is always non-negative.",
      explanation:"Absolute value removes the sign. |−38| = 38." },
    { id:"v32q0003", kind:"scored", topic:"numerical", subtopic:"GCF", difficulty:"medium",
      q:"What is the GCF of 36 and 48?",
      choices:["6","12","18","24"], answer:1,
      shortcut:"List factors of both and pick the largest common one.",
      explanation:"Factors of 36: 1,2,3,4,6,9,12,18,36. Factors of 48: 1,2,3,4,6,8,12,16,24,48. GCF=12." },
    { id:"v32q0004", kind:"scored", topic:"numerical", subtopic:"LCM", difficulty:"medium",
      q:"What is the LCM of 8 and 12?",
      choices:["16","24","32","48"], answer:1,
      shortcut:"LCM = (a × b) ÷ GCF.",
      explanation:"GCF of 8 and 12 = 4. LCM = (8×12)÷4 = 96÷4 = 24." },
    { id:"v32q0005", kind:"scored", topic:"clerical", subtopic:"Filing Rules", difficulty:"easy",
      q:"In alphabetical filing, which name comes FIRST?",
      choices:["Santos, Maria L.","Santos, Maria A.","Santos, Mario B.","Santos, M. A."], answer:1,
      shortcut:"File letter by letter. Compare same-length prefixes first.",
      explanation:"Among 'Santos, Maria', the middle initial A comes before L. Santos, Maria A. files first." },
    // WEEK 2: Fractions, Proportions
    { id:"v32q0006", kind:"scored", topic:"numerical", subtopic:"Fractions", difficulty:"easy",
      q:"Which fraction is equivalent to 3/4?",
      choices:["6/9","9/12","6/10","8/14"], answer:1,
      shortcut:"Multiply numerator and denominator by the same number.",
      explanation:"3/4 = (3×3)/(4×3) = 9/12." },
    { id:"v32q0007", kind:"scored", topic:"numerical", subtopic:"Proportion", difficulty:"medium",
      q:"If 4 workers can complete a task in 12 days, how many days will 6 workers take?",
      choices:["6","7","8","9"], answer:2,
      shortcut:"Inverse proportion: workers × days = constant.",
      explanation:"4 × 12 = 48 worker-days. 48 ÷ 6 = 8 days." },
    { id:"v32q0008", kind:"scored", topic:"numerical", subtopic:"Partitive Proportion", difficulty:"medium",
      q:"A sum of ₱1,800 is divided in the ratio 2:3:4. What is the largest share?",
      choices:["₱400","₱600","₱800","₱1,000"], answer:2,
      shortcut:"Divide total by sum of parts, multiply by largest part.",
      explanation:"Sum of parts = 2+3+4 = 9. Largest share = (4/9) × 1800 = 800." },
    // WEEK 3: Percentages
    { id:"v32q0009", kind:"scored", topic:"numerical", subtopic:"Percentage", difficulty:"easy",
      q:"What is 35% of 200?",
      choices:["60","65","70","75"], answer:2,
      shortcut:"35% = 35/100. Multiply: 200 × 0.35.",
      explanation:"200 × 0.35 = 70." },
    { id:"v32q0010", kind:"scored", topic:"numerical", subtopic:"Discount", difficulty:"medium",
      q:"A jacket worth ₱2,400 is on sale at 25% off. What is the sale price?",
      choices:["₱1,600","₱1,700","₱1,800","₱1,900"], answer:2,
      shortcut:"Sale price = original × (1 - discount%). Or: find discount and subtract.",
      explanation:"Discount = 0.25 × 2400 = 600. Sale price = 2400 - 600 = 1800." },
    { id:"v32q0011", kind:"scored", topic:"numerical", subtopic:"Percentage Change", difficulty:"medium",
      q:"A salary increased from ₱15,000 to ₱18,000. What is the percentage increase?",
      choices:["15%","18%","20%","25%"], answer:2,
      shortcut:"Percent change = (new − old) ÷ old × 100.",
      explanation:"(18000−15000)÷15000 × 100 = 3000÷15000 × 100 = 20%." },
    // WEEK 4: Exponents
    { id:"v32q0012", kind:"scored", topic:"numerical", subtopic:"Exponents", difficulty:"medium",
      q:"What is 2⁵ × 2³?",
      choices:["2⁷","2⁸","2¹⁵","4⁸"], answer:1,
      shortcut:"When multiplying same base, add exponents: aᵐ × aⁿ = aᵐ⁺ⁿ.",
      explanation:"2⁵ × 2³ = 2^(5+3) = 2⁸ = 256." },
    { id:"v32q0013", kind:"scored", topic:"numerical", subtopic:"Radicals", difficulty:"medium",
      q:"Simplify: √144",
      choices:["10","11","12","14"], answer:2,
      shortcut:"Know perfect squares up to 20.",
      explanation:"12 × 12 = 144, so √144 = 12." },
    // WEEK 4: SVA
    { id:"v32q0014", kind:"scored", topic:"verbal", subtopic:"Subject-Verb Agreement", difficulty:"easy",
      q:"Choose the correct sentence: The group of students _____ studying for the exam.",
      choices:["are","were","is","have been"], answer:2,
      shortcut:"Collective nouns like 'group' take singular verbs when acting as one unit.",
      explanation:"'Group' as a collective unit uses the singular verb 'is'." },
    { id:"v32q0015", kind:"scored", topic:"verbal", subtopic:"Subject-Verb Agreement", difficulty:"medium",
      q:"Neither the manager nor the employees _____ aware of the change.",
      choices:["is","are","was","were"], answer:1,
      shortcut:"With 'neither/nor', the verb agrees with the nearest subject.",
      explanation:"'Employees' (plural) is nearer to the verb. Use 'are'." },
    // WEEK 5: Motion
    { id:"v32q0016", kind:"scored", topic:"numerical", subtopic:"Motion Problems", difficulty:"medium",
      q:"A train travels 240 km in 3 hours. What is its average speed?",
      choices:["60 km/h","70 km/h","80 km/h","90 km/h"], answer:2,
      shortcut:"Speed = Distance ÷ Time.",
      explanation:"240 ÷ 3 = 80 km/h." },
    { id:"v32q0017", kind:"scored", topic:"numerical", subtopic:"Motion Problems", difficulty:"medium",
      q:"Two buses leave the same terminal going in opposite directions. One travels at 60 km/h and the other at 80 km/h. After 2 hours, how far apart are they?",
      choices:["140 km","240 km","280 km","300 km"], answer:2,
      shortcut:"Opposite directions: total distance = (speed1 + speed2) × time.",
      explanation:"(60 + 80) × 2 = 140 × 2 = 280 km." },
    // WEEK 5: Number Series
    { id:"v32q0018", kind:"scored", topic:"abstract", subtopic:"Number Series", difficulty:"easy",
      q:"What is the next number in the series: 3, 6, 12, 24, ___?",
      choices:["30","36","48","60"], answer:2,
      shortcut:"Check if each term is multiplied by a constant (geometric sequence).",
      explanation:"Each term is multiplied by 2: 3, 6, 12, 24, 48." },
    { id:"v32q0019", kind:"scored", topic:"abstract", subtopic:"Number Series", difficulty:"medium",
      q:"What is the next term: 1, 4, 9, 16, 25, ___?",
      choices:["30","34","36","40"], answer:2,
      shortcut:"Perfect squares: 1², 2², 3², 4², 5², 6²...",
      explanation:"The sequence is 1², 2², 3², 4², 5², so next is 6² = 36." },
    // WEEK 6: Age Problems
    { id:"v32q0020", kind:"scored", topic:"numerical", subtopic:"Age Problems", difficulty:"medium",
      q:"Liza is 4 years older than Ben. In 6 years, their ages will total 50. How old is Ben now?",
      choices:["16","17","18","19"], answer:1,
      shortcut:"Let Ben = x. Liza = x+4. Future: (x+6)+(x+10)=50.",
      explanation:"2x + 16 = 50, 2x = 34, x = 17. Ben is 17." },
    // WEEK 7: Work Problems
    { id:"v32q0021", kind:"scored", topic:"numerical", subtopic:"Work Problems", difficulty:"medium",
      q:"A can paint a wall in 6 hours, B can do it in 4 hours. How long will they take together?",
      choices:["1.8 hrs","2.0 hrs","2.4 hrs","2.8 hrs"], answer:2,
      shortcut:"Together rate = 1/a + 1/b. Time = 1 ÷ (1/a + 1/b).",
      explanation:"1/6 + 1/4 = 2/12 + 3/12 = 5/12. Time = 12/5 = 2.4 hrs." },
    // WEEK 7: Filipino
    { id:"v32q0022", kind:"scored", topic:"filipino", subtopic:"Nang o Ng", difficulty:"easy",
      q:"Piliin ang tamang sagot: Tumakbo siya nang _____ upang makahabol sa bus.",
      choices:["mabilis","mabilis na","mabilis na mabilis","mabilis-mabilis"], answer:0,
      shortcut:"Ang 'nang' ay ginagamit bago ang pang-abay (adverb). Tumakbo siya nang mabilis.",
      explanation:"Ginagamit ang 'nang' bago ang pang-abay na nagpapaliwanag kung paano ginawa ang kilos." },
    { id:"v32q0023", kind:"scored", topic:"filipino", subtopic:"Din o Rin", difficulty:"easy",
      q:"Anong tamang salita ang dapat gamitin: Pumunta _____ si Maria sa piknik.",
      choices:["din","rin","man","pa"], answer:1,
      shortcut:"Gamitin ang 'rin' kapag ang nakaraang salita ay nagtatapos sa patinig (a,e,i,o,u).",
      explanation:"'Maria' ay nagtatapos sa patinig 'a', kaya gamitin ang 'rin'. Pumunta rin si Maria." },
    // WEEK 8: Geometry
    { id:"v32q0024", kind:"scored", topic:"numerical", subtopic:"Geometry", difficulty:"medium",
      q:"A rectangle has a length of 12 m and a width of 7 m. What is its area?",
      choices:["38 m²","74 m²","84 m²","96 m²"], answer:2,
      shortcut:"Area of rectangle = length × width.",
      explanation:"12 × 7 = 84 m²." },
    { id:"v32q0025", kind:"scored", topic:"numerical", subtopic:"Pythagorean Theorem", difficulty:"medium",
      q:"A right triangle has legs of 3 cm and 4 cm. What is the length of the hypotenuse?",
      choices:["5 cm","6 cm","7 cm","8 cm"], answer:0,
      shortcut:"3-4-5 right triangle is a classic Pythagorean triple. Memorize it!",
      explanation:"c² = 3² + 4² = 9 + 16 = 25. c = √25 = 5 cm." },
    // WEEK 8: Assumptions & Conclusions
    { id:"v32q0026", kind:"scored", topic:"analytical", subtopic:"Assumptions and Conclusions", difficulty:"medium",
      q:"Statement: All government employees must file a SALN. Conclusion: Maria, a government employee, must file a SALN. Is the conclusion valid?",
      choices:["Yes, the conclusion follows logically.","No, the conclusion does not follow.","Cannot be determined.","The statement is false."], answer:0,
      shortcut:"Universal statement (All A are B) applies to every member of A.",
      explanation:"Since 'all government employees must file SALN' and Maria is a government employee, the conclusion is valid." },
    // WEEK 9: Statistics
    { id:"v32q0027", kind:"scored", topic:"numerical", subtopic:"Statistics", difficulty:"easy",
      q:"Find the median of: 4, 7, 2, 9, 5, 1, 8",
      choices:["4","5","6","7"], answer:1,
      shortcut:"Arrange in order and pick the middle value.",
      explanation:"Ordered: 1, 2, 4, 5, 7, 8, 9. Middle (4th) value = 5." },
    { id:"v32q0028", kind:"scored", topic:"numerical", subtopic:"Weighted Mean", difficulty:"medium",
      q:"A student scored 80 in a 3-unit subject and 92 in a 2-unit subject. What is the weighted mean?",
      choices:["84.4","85.0","85.2","86.0"], answer:0,
      shortcut:"Weighted mean = (sum of value × weight) ÷ (sum of weights).",
      explanation:"(80×3 + 92×2) ÷ (3+2) = (240+184) ÷ 5 = 424 ÷ 5 = 84.8 ≈ 84.4. Closest: 84.4." },
    // WEEK 9: Permutation
    { id:"v32q0029", kind:"scored", topic:"numerical", subtopic:"Permutation and Combination", difficulty:"medium",
      q:"In how many ways can 4 people be seated in a row?",
      choices:["12","16","24","48"], answer:2,
      shortcut:"Permutation with all n items = n! (n factorial).",
      explanation:"4! = 4 × 3 × 2 × 1 = 24." },
    // WEEK 10: Probability
    { id:"v32q0030", kind:"scored", topic:"numerical", subtopic:"Probability", difficulty:"medium",
      q:"A bag has 5 red and 3 blue balls. What is the probability of drawing a red ball?",
      choices:["3/8","5/8","5/3","3/5"], answer:1,
      shortcut:"P(event) = favorable outcomes ÷ total outcomes.",
      explanation:"P(red) = 5 ÷ (5+3) = 5/8." },
    { id:"v32q0031", kind:"scored", topic:"data", subtopic:"Probability", difficulty:"medium",
      q:"If a die is rolled once, what is the probability of getting an even number?",
      choices:["1/6","1/3","1/2","2/3"], answer:2,
      shortcut:"Even numbers on a die: 2, 4, 6 = 3 out of 6.",
      explanation:"P(even) = 3/6 = 1/2." },
    // WEEK 10: Sentence Correction
    { id:"v32q0032", kind:"scored", topic:"verbal", subtopic:"Sentence Correction", difficulty:"medium",
      q:"Which sentence contains a REDUNDANCY error?",
      choices:[
        "She returned the book to the library.",
        "He returned back home after the trip.",
        "They are planning a trip next summer.",
        "The committee reviewed the proposal."
      ], answer:1,
      shortcut:"Look for pairs that say the same thing (e.g., 'returned back').",
      explanation:"'Returned back' is redundant — 'returned' already implies going back." },
    // RA 6713 specific
    { id:"v32q0033", kind:"scored", topic:"general", subtopic:"RA 6713", difficulty:"medium",
      q:"Under RA 6713, how many working days does a public official have to respond to a request for information?",
      choices:["10 working days","15 working days","20 working days","30 working days"], answer:1,
      shortcut:"15 working days is the key RA 6713 response deadline.",
      explanation:"Section 5 of RA 6713 requires response within 15 working days from receipt of the request." },
    { id:"v32q0034", kind:"scored", topic:"general", subtopic:"RA 6713", difficulty:"medium",
      q:"SALN stands for ___.",
      choices:[
        "Statement of Assets, Liabilities, and Net Worth",
        "Schedule of Allowances, Leave, and Net Wages",
        "Standard Accountability for Legal Net Worth",
        "Summary of Assets, Loans, and Net Value"
      ], answer:0,
      shortcut:"SALN = Statement of Assets, Liabilities, and Net Worth.",
      explanation:"RA 6713 requires government employees to file SALN, disclosing their assets, liabilities, and net worth." },
    // Constitution
    { id:"v32q0035", kind:"scored", topic:"general", subtopic:"Philippine Constitution", difficulty:"easy",
      q:"Which branch of government has the power to declare war?",
      choices:["Executive","Legislative","Judicial","Civil Service Commission"], answer:1,
      shortcut:"Congress (Legislative) declares war; President commands the armed forces.",
      explanation:"Under Article VI, only Congress has the power to declare a state of war." },
    // Verbal Analogy
    { id:"v32q0036", kind:"scored", topic:"analytical", subtopic:"Verbal Analogy", difficulty:"medium",
      q:"DOCTOR : HOSPITAL :: TEACHER : ___",
      choices:["School","University","Classroom","Student"], answer:0,
      shortcut:"Find the relationship: person : place of work. Doctor works in a hospital. Teacher works in a school.",
      explanation:"A doctor works in a hospital; a teacher works in a school. Same relationship." },
    // Data Sufficiency
    { id:"v32q0037", kind:"scored", topic:"sufficiency", subtopic:"Data Sufficiency", difficulty:"hard",
      q:"Is x > 5?\nStatement 1: x² > 25\nStatement 2: x > 3",
      choices:[
        "Statement 1 alone is sufficient",
        "Statement 2 alone is sufficient",
        "Both statements together are sufficient",
        "Neither statement is sufficient"
      ], answer:2,
      shortcut:"x² > 25 means x > 5 OR x < -5. We need both to confirm x > 5.",
      explanation:"Statement 1 alone: x > 5 or x < -5, not sufficient alone. Statement 2 alone: x > 3, could be 4. Together: x > 3 AND x² > 25 → x must be > 5." },
    // Reading Comprehension
    { id:"v32q0038", kind:"scored", topic:"verbal", subtopic:"Reading Comprehension", difficulty:"medium",
      q:"The word 'ephemeral' most nearly means ___.",
      choices:["permanent","lasting","short-lived","significant"], answer:2,
      shortcut:"Ephemeral comes from Greek 'ephemeros' — lasting only a day.",
      explanation:"Ephemeral means short-lived or transitory, like a flower that blooms only one day." },
    // Venn Diagram
    { id:"v32q0039", kind:"scored", topic:"analytical", subtopic:"Venn Diagram", difficulty:"medium",
      q:"In a class of 40 students, 25 like Math and 20 like Science. If 10 like both, how many like neither?",
      choices:["3","5","7","10"], answer:1,
      shortcut:"Use |A ∪ B| = |A| + |B| − |A ∩ B|. Neither = Total − |A ∪ B|.",
      explanation:"|Math ∪ Science| = 25 + 20 − 10 = 35. Neither = 40 − 35 = 5." },
    // Double Negatives
    { id:"v32q0040", kind:"scored", topic:"verbal", subtopic:"Double Negatives", difficulty:"easy",
      q:"Which sentence is GRAMMATICALLY CORRECT?",
      choices:[
        "I don't have nothing to say.",
        "I don't have anything to say.",
        "I haven't got nothing to say.",
        "I have nothing to say not."
      ], answer:1,
      shortcut:"In standard English, avoid double negatives (don't + nothing).",
      explanation:"'I don't have anything' is correct. 'Don't + nothing' creates a double negative." }
  ];

  // Only add questions not already in the bank
  const existingIds = new Set(Q.map(q => q.id));
  const added = newQ.filter(q => !existingIds.has(q.id));
  Q.push(...added);
  console.log(`v32: Injected ${added.length} new questions.`);
})();
